/**
 * Embedded Issuer Root Certificate(s) — pinned trust anchor for offline
 * verification of TrustReceipt bundles + receipts.
 *
 * Consumers of `@agenticmcpstores/trust-receipt-verifier` use the active
 * embedded root as the trust anchor when validating the signed JWKS history
 * shipped alongside an export bundle. This avoids dependence on a live
 * `.well-known/jwks.json` fetch at verify time.
 *
 * Root rotation = SemVer bump of the verifier package: a new entry is
 * prepended to {@link EMBEDDED_ISSUER_ROOTS} (newest first) and the
 * previously-active entry's `validTo` is set to its retirement timestamp.
 *
 *  ("embedded issuer root cert + signed JWKS history")
 *  JWKS bundle trust anchor (resolves)
 *
 * STAGING NOTICE
 * ==============
 * The PEM constant below is a **STAGING-grade structural placeholder**.
 * The production-grade self-signed Ed25519 root is generated by an offline
 * key-ceremony in task; that ceremony output replaces this constant
 * before any production-trust use. Do NOT pin this stub as a production
 * trust anchor.
 *
 * TODO: swap `_STAGING_STUB_ROOT_PEM` and its `sha256` for the
 * ceremony-output cert (and bump `verifierMinVersion`).
 */

/**
 * One embedded root cert entry. Either currently active (`validTo === null`)
 * or retired (`validTo` set to the retirement instant in Unix seconds).
 */
export interface IssuerRootEntry {
  /** Self-signed Ed25519 cert (PEM-encoded). */
  readonly pem: string;
  /** SHA-256 of the PEM bytes (UTF-8), lowercase hex. */
  readonly sha256: string;
  /** Unix seconds — minimum issuance time this root may sign for. */
  readonly validFrom: number;
  /** Unix seconds — `null` if currently active (no expiry yet). */
  readonly validTo: number | null;
  /** Verifier-package SemVer that introduces this root entry. */
  readonly verifierMinVersion: string;
}

// ─── Staging stub PEM ─────────────────────────────────────────────────────────
//
// Structurally a valid X.509 PEM block (BEGIN CERTIFICATE / base64 body /
// END CERTIFICATE). The body bytes are deterministic placeholders — they do
// NOT decode to a verifying-capable Ed25519 public key, by design. Tests
// mock around this constant; the ceremony replaces it.

const _STAGING_STUB_ROOT_PEM = `-----BEGIN CERTIFICATE-----
MIIBKjCB3aADAgECAhRTcGVjMDQ5U3RhZ2luZ1N0dWJSdDAFBgMrZXAwLDEqMCgG
A1UEAwwhVHJ1c3RSZWNlaXB0IElzc3VlciBSb290IChTVEFHSU5HKTAeFw0yNjA1
MDQwMDAwMDBaFw00NjA1MDQwMDAwMDBaMCwxKjAoBgNVBAMMIVRydXN0UmVjZWlw
dCBJc3N1ZXIgUm9vdCAoU1RBR0lORykwKjAFBgMrZXADIQAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAADAFBgMrZXADQQDzZXJvLXNpZ25hdHVyZS1zdGFn
aW5nLXBsYWNlaG9sZGVyLXN3YXAtb24tcm90YXRpb24tdDQyMC1jZXJlbW9ueQAA
-----END CERTIFICATE-----
`;

/**
 * Pre-computed SHA-256 of `_STAGING_STUB_ROOT_PEM` (UTF-8 bytes).
 *
 * Deterministically reproducible:
 * `sha256(Buffer.from(pem, "utf8"))`.
 */
const _STAGING_STUB_ROOT_SHA256 =
  "6c8e57a39f46de1fe7698365fbd0c0031dc180719c2c656a73207a890f80d722";

/**
 * Active + recently-retired roots. Newest first.
 *
 * NOTE: Frozen at module load. Adding a new root is a SemVer bump of the
 * verifier package — no runtime mutation is supported.
 */
export const EMBEDDED_ISSUER_ROOTS: readonly IssuerRootEntry[] = Object.freeze([
  Object.freeze<IssuerRootEntry>({
    pem: _STAGING_STUB_ROOT_PEM,
    sha256: _STAGING_STUB_ROOT_SHA256,
    // 2026-05-04T00:00:00Z — staging cutover.
    validFrom: 1778198400,
    validTo: null,
    verifierMinVersion: "0.1.0",
  }),
]);

/**
 * Resolve a root by its SHA-256. Used when a bundle/receipt names a specific
 * root via the JWKS history's anchor reference.
 *
 * Lookup is case-insensitive on the input but compared in lowercase hex.
 *
 * @param sha256 Lowercase hex SHA-256 of the target PEM bytes.
 * @returns the matching {@link IssuerRootEntry} or `null` if not embedded.
 */
export function findIssuerRootBySha256(sha256: string): IssuerRootEntry | null {
  const needle = sha256.toLowerCase();
  for (const entry of EMBEDDED_ISSUER_ROOTS) {
    if (entry.sha256 === needle) {
      return entry;
    }
  }
  return null;
}

/**
 * Returns the currently active root — the unique entry with `validTo === null`.
 *
 * Invariant (enforced at SemVer-bump review time, not at runtime): exactly one
 * entry has `validTo === null`. If zero entries match, this throws — that
 * indicates a packaging error (no active root shipped) and verification cannot
 * proceed. If multiple entries match, the first (newest) is returned.
 *
 * @throws {Error} `"No active issuer root"` when zero entries are active.
 */
export function getActiveIssuerRoot(): IssuerRootEntry {
  for (const entry of EMBEDDED_ISSUER_ROOTS) {
    if (entry.validTo === null) {
      return entry;
    }
  }
  throw new Error("No active issuer root");
}

// ─── Chain validation ─────────────────────────────────────────────────────────

/** One validation failure found by {@link validateChain}. */
export interface ValidateChainError {
  /** Index into the `roots` array, or -1 for list-level errors. */
  index: number;
  reason: string;
}

/** Result of {@link validateChain}. */
export interface ValidateChainResult {
  valid: boolean;
  errors: ValidateChainError[];
}

/**
 * Validate a chain of issuer root entries for structural correctness:
 *  1. Exactly one entry must have `validTo === null` (the active root).
 *  2. Entries must be ordered newest-first by `validFrom`.
 *  3. Every retired entry must have `validTo >= validFrom`.
 *
 * Intended for use in CI and package-release gates, not in the hot verify path.
 */
export function validateChain(
  roots: readonly IssuerRootEntry[]
): ValidateChainResult {
  const errors: ValidateChainError[] = [];

  const activeCount = roots.filter((r) => r.validTo === null).length;
  if (activeCount === 0) {
    errors.push({ index: -1, reason: "No active root (validTo === null)" });
  } else if (activeCount > 1) {
    errors.push({
      index: -1,
      reason: `${activeCount} active roots — exactly one allowed`,
    });
  }

  for (let i = 0; i < roots.length; i++) {
    const entry = roots[i];
    if (!entry) continue;
    if (entry.validTo !== null && entry.validTo < entry.validFrom) {
      errors.push({
        index: i,
        reason: `validTo=${entry.validTo} < validFrom=${entry.validFrom}`,
      });
    }
    if (i > 0) {
      const prev = roots[i - 1];
      if (prev && prev.validFrom < entry.validFrom) {
        errors.push({
          index: i,
          reason: `Root[${i - 1}].validFrom=${prev.validFrom} < Root[${i}].validFrom=${entry.validFrom} — list must be newest-first`,
        });
      }
    }
  }

  return { valid: errors.length === 0, errors };
}
